Fix `riemann-haproxy` NoMethodError
Previous refactoring was intended to make the code testable to unbreak
it, but a copy/paste error in the non-tested code path was introduced
causing an exception at runtime:

```
NoMethodError undefined method `body' for nil:NilClass
```

Move the line at the right position where `res` is available.